GestionnaireVideothequeApp/Controllers/ExemplaireController.cs
using GestionnaireVideothequeApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GestionnaireVideothequeApp.Controllers
{
    public class ExemplaireController : Controller
    {
        private GestionnaireVideothequeDBEntities _db = new GestionnaireVideothequeDBEntities();

        // GET: Exemplaire
        public ActionResult Index()
        {
            return View(_db.EXEMPLAIRE.ToList());
        }

        // GET: Exemplaire/Details/5
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EXEMPLAIRE exemplaire = _db.EXEMPLAIRE.Find(id);
            if(exemplaire == null)
            {
                return HttpNotFound();
            }
            return View(exemplaire);
        }

        // GET: Exemplaire/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Exemplaire/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "EXEMPLAIREID")] EXEMPLAIRE ExemplaireToCreate)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // On ajoute le nouvel exemplaire à la collection d'exemplaires
                _db.EXEMPLAIRE.Add(ExemplaireToCreate);

                // On sauvegarde
                _db.SaveChanges();

                // On redirige vers la vue Index
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Exemplaire/Edit/5
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ExemplaireToEdit = (from e in _db.EXEMPLAIRE
                                    where e.EXEMPLAIREID == id
                                    select e).First();

            if(ExemplaireToEdit == null)
            {
                return HttpNotFound();
            }

            return View(ExemplaireToEdit);
        }

        // POST: Exemplaire/Edit/5
        [HttpPost]
        public ActionResult Edit(EXEMPLAIRE ExemplaireToEdit)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // TODO: Add update logic here
                _db.Entry(ExemplaireToEdit).State = EntityState.Modified;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch 
            {
                return View();
            }
        }

        // GET: Exemplaire/Delete/5
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EXEMPLAIRE exemplaire = _db.EXEMPLAIRE.Find(id);
            if(exemplaire == null)
            {
                return HttpNotFound();
            }

            return View(exemplaire);
        }

        // POST: Exemplaire/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // Ici on supprime l'enregistrement
                EXEMPLAIRE exemplaire = _db.EXEMPLAIRE.Find(id);
                _db.EXEMPLAIRE.Remove(exemplaire);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestionnaireVideothequeApp/Controllers/FactureController.cs
using GestionnaireVideothequeApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GestionnaireVideothequeApp.Controllers
{
    public class FactureController : Controller
    {
        private GestionnaireVideothequeDBEntities _db = new GestionnaireVideothequeDBEntities();

        // GET: Facture
        public ActionResult Index()
        {
            return View(_db.FACTURE.ToList());
        }

        // GET: Facture/Details/5
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            FACTURE facture = _db.FACTURE.Find(id);
            if (facture == null)
            {
                return HttpNotFound();
            }

            return View(facture);
        }

        // GET: Facture/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Facture/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "FACTUREID")] FACTURE FactureToCreate)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // On ajoute la nouvelle facture à la collection de factures
                _db.FACTURE.Add(FactureToCreate);

                // On sauvegarde
                _db.SaveChanges();

                // On redirige vers la vue Index

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Facture/Edit/5
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var FactureToEdit = (from f in _db.FACTURE
                                 where f.FACTUREID == id
                                 select f).First();

            if(FactureToEdit == null)
            {
                return HttpNotFound();
            }

            return View(FactureToEdit);
        }

        // POST: Facture/Edit/5
        [HttpPost]
        public ActionResult Edit(FACTURE FactureToEdit)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // TODO: Add update logic here
                _db.Entry(FactureToEdit).State = EntityState.Modified;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch 
            {
                return View();
            }
        }

        // GET: Facture/Delete/5
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            FACTURE facture = _db.FACTURE.Find(id);
            if(facture == null)
            {
                return HttpNotFound();
            }

            return View(facture);
        }

        // POST: Facture/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // Ici on supprime l'enregistrement
                FACTURE facture = _db.FACTURE.Find(id);
                _db.FACTURE.Remove(facture);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestionnaireVideothequeApp/Controllers/HomeController.cs
using GestionnaireVideothequeApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace GestionnaireVideothequeApp.Controllers
{
    public class HomeController : Controller
    {
        private GestionnaireVideothequeDBEntities _db = new GestionnaireVideothequeDBEntities();

        // GET Accueil
        public ActionResult Accueil()
        {
            return View("Accueil");
        }

        // GET About
        public ActionResult About()
        {
            return View("About");
        }

        // GET Contact
        public ActionResult Contact()
        {
            return View("Contact");
        }

        // GET: Home
        public ActionResult Index()
        {
            return View(_db.FILM.ToList());
        }

        // GET: Home/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            FILM film = _db.FILM.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // GET: Home/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "FILMID")] FILM FilmToCreate)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // On ajoute le nouvel exemplaire à la collection d'exemplaires
                _db.FILM.Add(FilmToCreate);

                // On sauvegarde
                _db.SaveChanges();

                // On redirige vers la vue Index
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Search()
        {
            return View();
        }
        // GET Search
        [HttpGet]
        public async Task<ActionResult> SearchByName(string searchName)
        {
            ViewData["GetFilmByName"] = searchName;

            var query = from n in _db.FILM select n;
            if (!String.IsNullOrEmpty(searchName))
            {
                query = query.Where(n => n.NOMFILM.Contains(searchName));
            }
            return View(await query.AsNoTracking().ToListAsync());
        }

        // GET Search
        [HttpGet]
        public async Task<ActionResult> SearchByCategory(string searchCategory)
        {
            ViewData["GetFilmByCategory"] = searchCategory;

            var query = from c in _db.FILM select c;
            if (!String.IsNullOrEmpty(searchCategory))
            {
                query = query.Where(c => c.CATEGORIE.Contains(searchCategory));
            }
            return View(await query.AsNoTracking().ToListAsync());

        }// GET Search
        [HttpGet]
        public async Task<ActionResult> SearchByRealisator(string searchRealisator)
        {
            ViewData["GetFilmByRealisator"] = searchRealisator;

            var query = from r in _db.FILM select r;

            if (!String.IsNullOrEmpty(searchRealisator))
            {
                query = query.Where(r => r.REALISATEUR.Contains(searchRealisator));
            }
            return View(await query.AsNoTracking().ToListAsync());

        }
        
        // GET Search
        [HttpGet]
        public async Task<ActionResult> SearchByDate(string searchDate)
        {
            ViewData["GetFilmByDate"] = searchDate;

            var query = from n in _db.FILM select n;
            if (!String.IsNullOrEmpty(searchDate))
            {
                query = query.Where(n => n.DATESORTIE.ToString().Contains(searchDate));
            }
            return View(await query.AsNoTracking().ToListAsync());
        }




        // GET: Home/Edit/5
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var FilmToEdit = (from f in _db.FILM
                              where f.FILMID == id
                              select f).First();

            if(FilmToEdit == null)
            {
                return HttpNotFound();
            }

            return View(FilmToEdit);
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit(FILM FilmToEdit)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // TODO: Add update logic here
                _db.Entry(FilmToEdit).State = System.Data.Entity.EntityState.Modified;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch 
            {
                return View();
            }
        }
        
        // GET: Home/Delete/5
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            FILM film = _db.FILM.Find(id);
            if(film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // POST: Home/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // TODO: Add delete logic here
                FILM film = _db.FILM.Find(id);
                _db.FILM.Remove(film);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestionnaireVideothequeApp/Controllers/TarifController.cs
using GestionnaireVideothequeApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GestionnaireVideothequeApp.Controllers
{
    public class TarifController : Controller
    {
        private GestionnaireVideothequeDBEntities _db = new GestionnaireVideothequeDBEntities();

        // GET: Tarif
        public ActionResult Index()
        {
            return View(_db.TARIF.ToList());
        }

        // GET: Tarif/Details/5
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TARIF tarif = _db.TARIF.Find(id);
            if(tarif == null)
            {
                return HttpNotFound();
            }
            return View(tarif);
        }

        // GET: Tarif/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tarif/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "TARIFID")] TARIF TarifToCreate)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // On ajoute le nouveau tarif à la collection de tarifs
                _db.TARIF.Add(TarifToCreate);

                // On sauvegarde
                _db.SaveChanges();

                // On redirige vers la vue Index

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Tarif/Edit/5
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var TarifToEdit = (from t in _db.TARIF
                               where t.TARIFID == id
                               select t).First();

            if(TarifToEdit == null)
            {
                return HttpNotFound();
            }

            return View(TarifToEdit);
        }

        // POST: Tarif/Edit/5
        [HttpPost]
        public ActionResult Edit(TARIF TarifToEdit)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // TODO: Add update logic here
                _db.Entry(TarifToEdit).State = System.Data.Entity.EntityState.Modified;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch 
            {
                return View();
            }
        }

        // GET: Tarif/Delete/5
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TARIF tarif = _db.TARIF.Find(id);
            if(tarif == null)
            {
                return HttpNotFound();
            }

            return View(tarif);
        }

        // POST: Tarif/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // Ici on supprime l'enregistrement
                TARIF tarif = _db.TARIF.Find(id);
                _db.TARIF.Remove(tarif);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestionnaireVideothequeApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "A propos de";
}

<h2>A propos de nous</h2>
<p>
    Nous vous souhaitons une bonne présentation.
</p>

GestionnaireVideothequeApp/Views/Home/Accueil.cshtml
<head>
    <style>
        .boutonmenuprincipal {
            background-color: #e83737;
            color: white;
            border: none;
            cursor: pointer;
            padding: 20px;
            margin-top: 20px;
            font-size: 30px;
        }

            .boutonmenuprincipal:hover {
                background-color: #ff4444;
            }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-child {
            display: none;
            background-color: #f28c8c;
            min-width: 50px;
        }

            .dropdown-child a {
                color: white;
                padding: 20px;
                text-decoration: none;
                display: block;
            }

        .dropdown:hover .dropdown-child {
            display: block;
        }
    </style>
</head>
@{
    ViewBag.Title = "Accueil";
}
<h1>Gestionnaire de Vidéothèque</h1>



<a href="Create"><input type="submit" value="Ajouter un film" class="btn btn-primary" /></a>
@Html.ActionLink("Liste des exemplaires", "Index", "Exemplaire") | | @Html.ActionLink("Factures", "Index", "Facture") | | @Html.ActionLink("Tarifs", "Index", "Tarif") 

GestionnaireVideothequeApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h2>Contact</h2>
<ul>
    <li>Thibault Pares : <a href="https://github.com/Quarren">Github</a></li>
    <li>Nozithello Ncube : <a href="https://github.com/NozitheloNcube">Github</a></li>
    <li>Kevin Daniel : <a href="https://github.com/DnlKevin">Github</a></li>
</ul>

GestionnaireVideothequeApp/Views/Home/Create.cshtml
@model GestionnaireVideothequeApp.Models.FILM

@{
    ViewBag.Title = "Ajouter un film";
}
<h2>Ajouter un film</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
   
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.NOMFILM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NOMFILM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NOMFILM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CATEGORIE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CATEGORIE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CATEGORIE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.REALISATEUR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.REALISATEUR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.REALISATEUR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DATESORTIE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DATESORTIE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DATESORTIE, "Format : dd-mm-yyyy", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour à la liste des films", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionnaireVideothequeApp/Views/Home/Delete.cshtml
@model GestionnaireVideothequeApp.Models.FILM

@{
    ViewBag.Title = "Supprimer un film";
}


<h3>Êtes-vous sûr(e) de vouloir supprimer ce film ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            ID :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FILMID)
        </dd>

        <dt>
            Nom :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMFILM)
        </dd>

        <dt>
            Catégorie :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIE)
        </dd>

        <dt>
            Réalisateur :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.REALISATEUR)
        </dd>

        <dt>
            Date de sortie :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATESORTIE)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste des films", "Index")
        </div>
    }
</div>

GestionnaireVideothequeApp/Views/Home/Details.cshtml
@model GestionnaireVideothequeApp.Models.FILM

@{
    ViewBag.Title = "Details";
}

<h2>Détails à propos de : <h4>@Html.DisplayFor(model => model.NOMFILM)</h4> </h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            ID :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FILMID)
        </dd>


        <dt>
            Nom :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMFILM)
        </dd>

        <dt>
            Catégorie :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIE)
        </dd>

        <dt>
            Réalisateur :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.REALISATEUR)
        </dd>

        <dt>
            Date de sortie :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATESORTIE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editer", "Edit", new { id = Model.FILMID }) |
    @Html.ActionLink("Retour à la liste des films", "Index")
</p>

GestionnaireVideothequeApp/Views/Home/Edit.cshtml
@model GestionnaireVideothequeApp.Models.FILM

@{
    ViewBag.Title = "Edit";
}

<h2>Editer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.FILMID)

    <div class="form-group">
        @Html.LabelFor(model => model.FILMID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FILMID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FILMID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NOMFILM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NOMFILM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NOMFILM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CATEGORIE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CATEGORIE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CATEGORIE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.REALISATEUR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.REALISATEUR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.REALISATEUR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DATESORTIE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DATESORTIE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DATESORTIE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour à la liste de films", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionnaireVideothequeApp/Views/Home/Index.cshtml
@model IEnumerable<GestionnaireVideothequeApp.Models.FILM>

@{
    ViewBag.Title = "Index";
}

<h2>Liste des films de la vidéothèque</h2>
<br />
@Html.ActionLink("Ajouter un film", "Create", "Home") 


<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            Nom
        </th>
        <th>
            Catégorie
        </th>
        <th>
            Réalisateur
        </th>
        <th>
            Date de sortie
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.FILMID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NOMFILM)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CATEGORIE)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.REALISATEUR)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DATESORTIE)
    </td>
    <td>
        <!--NE PAS MODIFIER-->
        @Html.ActionLink("Editer", "Edit", new { id = item.FILMID }) |
        @Html.ActionLink("Détails", "Details", new { id = item.FILMID }) |
        @Html.ActionLink("Supprimer", "Delete", new { id = item.FILMID })
    </td>
</tr>
    }

</table>

GestionnaireVideothequeApp/Views/Home/SearchByCategory.cshtml
@model IEnumerable<GestionnaireVideothequeApp.Models.FILM>

@{
    ViewBag.Title = "SearchByCategory";
}

<h2>Recherche par catégorie</h2>
<br />
<form method="get" asp-action="Search">
    <p>
        <!-- <select name="search-filter" size="1">
        <option value="1">Nom</option>
        <option value="2">Catégorie</option>
        <option value="3">Réalisateur</option>
        <option value="4">Année</option>
    </select>-->

        <input type="search" placeholder="Cherchez par catégorie" value="@ViewData["GetFilmByCategory"]" name="searchCategory" style="width:500px;" />
        <input type="submit" value="Rechercher" class="btn btn-primary" />
        <a href="SearchByName">Nom</a> | <a href="SearchByCategory">Catégorie</a> | <a href="SearchByRealisator">Réalisateur</a> | <a href="SearchByDate">Date</a>

    </p>

</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NOMFILM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CATEGORIE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.REALISATEUR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATESORTIE)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NOMFILM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CATEGORIE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.REALISATEUR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DATESORTIE)
            </td>

        </tr>
    }

</table>