GestionnaireVideothequeApp/Models/LOCATION.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireVideothequeApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class LOCATION
    {
        [Key]
        public int LOCATIONID { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DATEDEBUT { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DATEFIN { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DATERETOUREFF { get; set; }
        public int MONTANT { get; set; }

        //Relationships
        public List<EXEMPLAIRE> Exemplaires { get; set; }
        public List<FACTURE> Factures { get; set; }
        public List<CLIENT> Clients { get; set; }

        [ForeignKey("EXEMPLAIREID")]
        public int EXEMPLAIREID { get; set; }
        public EXEMPLAIRE Exemplaire { get; set; }
        
        [ForeignKey("FACTUREID")]
        public int FACTUREID { get; set; }
        public FACTURE Facture { get; set; }

        [ForeignKey("CLIENTID")]
        public int CLIENTID { get; set; }
        public CLIENT Client { get; set; }

    }
}

GestionnaireVideothequeApp/Controllers/LocationController.cs
using GestionnaireVideothequeApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace GestionnaireVideothequeApp.Controllers
{
    public class LocationController : Controller
    {
        private GestionnaireVideothequeDBEntities _db = new GestionnaireVideothequeDBEntities();
       


        // GET: Location
        public ActionResult Index()
        {
            return View(_db.LOCATION.ToList());
        }

        
        // GET Search
        [HttpGet]
        public async Task<ActionResult> LocationEnCours(String date)
        {

            ViewData["GetLocationEnCours"] = date;

            var query = from l in _db.LOCATION
                        where l.DATERETOUREFF == null
                        select l;

            return View(query);
        }

        // GET: Location/Details/5
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            LOCATION location = _db.LOCATION.Find(id);
            if(location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Location/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Location/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "LOCATIONID")] LOCATION LocationToCreate)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // On ajoute la nouvelle location à la collection de locations
                _db.LOCATION.Add(LocationToCreate);

                // On sauvegarde
                _db.SaveChanges();

                // On redirige vers la vue Index

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Location/Edit/5
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var LocationToEdit = (from l in _db.LOCATION
                                  where l.LOCATIONID == id
                                  select l).First();

            if(LocationToEdit == null)
            {
                return HttpNotFound();
            }

            return View(LocationToEdit);
        }

        // POST: Location/Edit/5
        [HttpPost]
        public ActionResult Edit(LOCATION LocationToEdit)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // TODO: Add update logic here
                _db.Entry(LocationToEdit).State = EntityState.Modified;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch 
            {
                return View();
            }
        }

        // GET: Location/Delete/5
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            LOCATION location = _db.LOCATION.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Location/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // Ici on supprime l'enregistrement
                LOCATION location = _db.LOCATION.Find(id);
                _db.LOCATION.Remove(location);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestionnaireVideothequeApp/Views/Location/Create.cshtml
@model GestionnaireVideothequeApp.Models.LOCATION

@{
    ViewBag.Title = "Create";
}

<h2>Ajouter une location</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DATEDEBUT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATEDEBUT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATEDEBUT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATEFIN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATEFIN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATEFIN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATERETOUREFF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATERETOUREFF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATERETOUREFF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MONTANT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MONTANT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MONTANT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste des locations", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionnaireVideothequeApp/Views/Location/Delete.cshtml
@model GestionnaireVideothequeApp.Models.LOCATION

@{
    ViewBag.Title = "Delete";
}

<h2>Supprimer cette location</h2>

<h3>Êtes-vous sûr(e) de vouloir supprimer cette location ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LOCATIONID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOCATIONID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATEDEBUT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATEDEBUT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATEFIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATEFIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATERETOUREFF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATERETOUREFF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MONTANT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MONTANT)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste des locations", "Index")
        </div>
    }
</div>

GestionnaireVideothequeApp/Views/Location/Details.cshtml
@model GestionnaireVideothequeApp.Models.LOCATION

@{
    ViewBag.Title = "Details";
}

<h2>Détails</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LOCATIONID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOCATIONID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATEDEBUT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATEDEBUT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATEFIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATEFIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATERETOUREFF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATERETOUREFF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MONTANT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MONTANT)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editer", "Edit", new { id = Model.LOCATIONID }) |
    @Html.ActionLink("Retour à la liste des locations", "Index")
</p>

GestionnaireVideothequeApp/Views/Location/Edit.cshtml
@model GestionnaireVideothequeApp.Models.LOCATION

@{
    ViewBag.Title = "Edit";
}

<h2>Editer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.LOCATIONID)

    <div class="form-group">
        @Html.LabelFor(model => model.LOCATIONID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LOCATIONID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LOCATIONID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DATEDEBUT, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DATEDEBUT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DATEDEBUT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DATEFIN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DATEFIN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DATEFIN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DATERETOUREFF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DATERETOUREFF, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DATERETOUREFF, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MONTANT, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MONTANT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MONTANT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour à la liste des locations", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionnaireVideothequeApp/Views/Location/Index.cshtml
@model IEnumerable<GestionnaireVideothequeApp.Models.LOCATION>

@{
    ViewBag.Title = "Index";
}

<h2>Locations</h2>

<br/>

<p>
    @Html.ActionLink("Ajouter une nouvelle location", "Create", "Location") | @Html.ActionLink("Voir les locations en cours", "LocationEnCours", "Location")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LOCATIONID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATEDEBUT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATEFIN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATERETOUREFF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MONTANT)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.LOCATIONID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DATEDEBUT)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DATEFIN)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DATERETOUREFF)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MONTANT)
    </td>
    <td>
        @Html.ActionLink("Editer", "Edit", new { id = item.LOCATIONID }) |
        @Html.ActionLink("Détails", "Details", new { id = item.LOCATIONID }) |
        @Html.ActionLink("Supprimer", "Delete", new { id = item.LOCATIONID })
    </td>
</tr>
}

</table>

GestionnaireVideothequeApp/Views/Location/LocationEnCours.cshtml
@model IEnumerable<GestionnaireVideothequeApp.Models.LOCATION>

@{
    ViewBag.Title = "LocationEnCours";
}

<h2>Locations en cours</h2>
<br/>

<p>
    @Html.ActionLink("Ajouter une nouvelle location", "Create") | @Html.ActionLink("Retour à la liste des locations", "Index", "Location")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DATEDEBUT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATEFIN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATERETOUREFF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MONTANT)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DATEDEBUT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DATEFIN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DATERETOUREFF)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MONTANT)
        </td>
        <td>
            @Html.ActionLink("Editer", "Edit", new { id=item.LOCATIONID }) |
            @Html.ActionLink("Détails", "Details", new { id=item.LOCATIONID }) |
            @Html.ActionLink("Supprimer", "Delete", new { id=item.LOCATIONID })
        </td>
    </tr>
}

</table>