GestionnaireVideothequeApp/Models/CLIENT.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireVideothequeApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENT
    {
        [Key]
        public int CLIENTID { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DATENAISSANCE { get; set; }
        public string NUMEROTEL { get; set; }
        public string ADRESSE { get; set; }
        public string MAIL { get; set; }
    }
}

GestionnaireVideothequeApp/Controllers/ClientController.cs
using GestionnaireVideothequeApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace GestionnaireVideothequeApp.Controllers
{
    public class ClientController : Controller
    {
        private GestionnaireVideothequeDBEntities _db = new GestionnaireVideothequeDBEntities();

        public object EXEMPLAIREID { get; private set; }
        public int CLIENTID { get; private set; }

        // GET Films loués par un client
        [HttpGet]
        public async Task<ActionResult> LocParClient(string id)
        {
            // Requête SQL pour la 4 :
            // SELECT* FROM EXEMPLAIRES 
            //  WHERE ExemplaireId IN
            // (SELECT ExemplaireId FROM LOCATIONS WHERE ClientId LIKE<ClientId passé en paramètre>)
            ViewData["GetLocParClient"] = id;

            var query =
                (from EXEMPLAIRE in _db.LOCATION
                 where EXEMPLAIREID != null
                 select EXEMPLAIRE);

            var query2 =
                (from LOCATION in _db.LOCATION
                 where CLIENTID.ToString() == id
                 select CLIENTID);
                  
        if(query != query2)
            {
                System.Console.WriteLine("Ce client n'a pas de locations");
                return View(await query.AsNoTracking().ToListAsync());

            } else
            {
                return View(await query.AsNoTracking().ToListAsync());
            }
        }

        // GET: Client
        public ActionResult Index()
        {
            return View(_db.CLIENT.ToList());
        }

        // GET: Client/Details/5
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CLIENT client = _db.CLIENT.Find(id);
            if(client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Client/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Client/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "CLIENTID")] CLIENT ClientToCreate)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // On ajoute le nouveau client à la collection de clients
                _db.CLIENT.Add(ClientToCreate);

                // On sauvegarde
                _db.SaveChanges();

                // On redirige vers la vue Index

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ClientToEdit = (from c in _db.CLIENT
                                where c.CLIENTID == id
                                select c).First();

            if(ClientToEdit == null)
            {
                return HttpNotFound();
            }

            return View(ClientToEdit);
        }

        // POST: Client/Edit/5
        [HttpPost]
        public ActionResult Edit(CLIENT ClientToEdit)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                // TODO: Add update logic here
                _db.Entry(ClientToEdit).State = EntityState.Modified;
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch 
            {
                return View();
            }
        }

        // GET: Client/Delete/5
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CLIENT client = _db.CLIENT.Find(id);
            if(client == null)
            {
                return HttpNotFound();
            }

            return View(client);
        }

        // POST: Client/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // Ici on supprime l'enregistrement
                CLIENT client = _db.CLIENT.Find(id);
                _db.CLIENT.Remove(client);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestionnaireVideothequeApp/Views/Client/Create.cshtml
@model GestionnaireVideothequeApp.Models.CLIENT

@{
    ViewBag.Title = "Create";
}

<h2>Ajouter un client</h2>
<br />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NOM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRENOM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRENOM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRENOM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATENAISSANCE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATENAISSANCE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATENAISSANCE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NUMEROTEL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NUMEROTEL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NUMEROTEL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ADRESSE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ADRESSE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ADRESSE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste des clients", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionnaireVideothequeApp/Views/Client/Delete.cshtml
@model GestionnaireVideothequeApp.Models.CLIENT

@{
    ViewBag.Title = "Delete";
}

<h2>Supprimer le client</h2>

<h3>Êtes-vous sûr(e) de vouloir supprimer ce client de la base de données ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CLIENTID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLIENTID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NOM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRENOM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRENOM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATENAISSANCE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATENAISSANCE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NUMEROTEL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NUMEROTEL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ADRESSE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ADRESSE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MAIL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste des clients", "Index")
        </div>
    }
</div>

GestionnaireVideothequeApp/Views/Client/Details.cshtml
@model GestionnaireVideothequeApp.Models.CLIENT

@{
    ViewBag.Title = "Details";
}

<h2>Détails</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CLIENTID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLIENTID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NOM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRENOM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRENOM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATENAISSANCE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATENAISSANCE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NUMEROTEL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NUMEROTEL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ADRESSE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ADRESSE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MAIL)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editer", "Edit", new { id = Model.CLIENTID }) |
    @Html.ActionLink("Retour à la liste des clients", "Index")
</p>

GestionnaireVideothequeApp/Views/Client/Edit.cshtml
@model GestionnaireVideothequeApp.Models.CLIENT

@{
    ViewBag.Title = "Edit";
}

<h2>Editer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CLIENTID)

<div class="form-group">
    @Html.LabelFor(model => model.CLIENTID, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.CLIENTID, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NOM, "", new { @class = "text-danger" })
    </div>
</div>

    <div class="form-group">
        @Html.LabelFor(model => model.NOM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NOM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NOM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PRENOM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PRENOM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PRENOM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DATENAISSANCE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DATENAISSANCE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DATENAISSANCE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NUMEROTEL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NUMEROTEL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NUMEROTEL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ADRESSE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ADRESSE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ADRESSE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MAIL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MAIL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MAIL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour à la liste des clients", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionnaireVideothequeApp/Views/Client/Index.cshtml
@model IEnumerable<GestionnaireVideothequeApp.Models.CLIENT>

@{
    ViewBag.Title = "Index";
}

<h2>Clients</h2>
<br />
<p>
    @Html.ActionLink("Ajouter un client", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CLIENTID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NOM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PRENOM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATENAISSANCE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NUMEROTEL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ADRESSE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MAIL)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <th>
        @Html.DisplayFor(modelItem => item.CLIENTID)
    </th>
    <td>
        @Html.DisplayFor(modelItem => item.NOM)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PRENOM)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DATENAISSANCE)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NUMEROTEL)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ADRESSE)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MAIL)
    </td>
    <td>
        @Html.ActionLink("Locations en cours", "LocParClient", "Client") |
        @Html.ActionLink("Editer", "Edit", new { id = item.CLIENTID }) |
        @Html.ActionLink("Détails", "Details", new { id = item.CLIENTID }) |
        @Html.ActionLink("Supprimer", "Delete", new { id = item.CLIENTID })
    </td>
</tr>
}

</table>

GestionnaireVideothequeApp/Views/Client/LocParClient.cshtml
@model IEnumerable<GestionnaireVideothequeApp.Models.LOCATION>

@{
    ViewBag.Title = "LocParClient";
}

<h2>LocParClient</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DATEDEBUT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATEFIN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATERETOUREFF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MONTANT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EXEMPLAIREID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FACTUREID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CLIENTID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DATEDEBUT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DATEFIN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DATERETOUREFF)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MONTANT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EXEMPLAIREID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FACTUREID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CLIENTID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LOCATIONID }) |
            @Html.ActionLink("Details", "Details", new { id=item.LOCATIONID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LOCATIONID })
        </td>
    </tr>
}

</table>